#+title: Style Guide
#+author: Rich Loveland
#+email: r@rmloveland.com

Follow these guidelines when editing the Texinfo-formatted version of
the scsh manual.

* The name of scsh

  The name of =scsh= is lowercased, as with other shells such as
  =bash=. Please change all references to reflect this (except when
  occurring at the beginning of a sentence).

* Scsh/Scheme 48 Records

  Mentions of scsh record names or fields will use the `@code{}'
  notation.
  
* Capitalization

  Procedure and macro names will be capitalized if they appear at the
  beginning of a sentence (a la SICP).

  The acronym ``VM'' will be uppercased.

* Procedure return values

  All procedure definition blocks will show a return value, just like
  in the TeX version.

* Book Titles

  Book titles will use the `@emph{}' command.

* Miscellaneous Conventions

  - `filename' is one word; `file name' and `file-name' will not be
    used except in procedure and variable names.

  - `whitespace' is one word.

  - `char-set' is the only acceptable usage other than ``character set''.

  - Paragraphs are filled using `M-q'. Auto-fill-mode may have
    unexpected results on code examples.

  - Sections marked `Note' use simple emphasis only on the first word.
* UNIX

  UNIX (all caps) is a trademarked name, and should be denoted as
  such.  An alternative would be to use the phrases/terms
  ``UNIX-like'', ``Unix'', ``unix'', or something along those lines.
